client:
    build: .
    ports:
        - "4200:4200"   # Default port for dev webserver
        - "49153:49153" # Live Reload Port
    volumes:
        - /usr/src/app/node_modules
        - .:/usr/src/app
    command: npm start
