apiVersion: v1
kind: Service
metadata:
  name: webserver-service
  labels:
    name: webserver
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    name: webserver
