apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: api
    spec:
      containers:
      - image: angmerica/todo-client:api-develop-${CIRCLE_SHA1}
        name: api
        ports:
        - name: http-server
          containerPort: 9000
        env:
        - name: database_hostname
          value: "mongodb://mongo:27017"
        - name: NODE_ENV
          value: "integration"
