apiVersion: v1
kind: Service
metadata:
  name: api-service
  labels:
    name: api
spec:
  ports:
  - port: 9000
    targetPort: 9000
    protocol: TCP
  selector:
    name: api

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: api
    spec:
      containers:
      - image: api:v1
        name: api
        ports:
        - name: http-server
          containerPort: 9000
        env:
        - name: database_hostname
          value: "mongodb://mongo-service:27017"