apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: webserver
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: webserver
    spec:
      containers:
      - image: ${IMAGE_REPO}${IMAGE_TAG}${CIRCLE_SHA1}
        imagePullPolicy: Always
        name: webserver
        ports:
        - name: http-server
          containerPort: 80
          hostPort: 80
        env:
        - name: NODE_ENV
          value: "integration"
